#!/bin/bash
# Check the RAW webhook logs on the server
# This shows ALL HTTP requests received, regardless of processing success

echo "=== Checking RAW Webhook Logs on Server ==="
echo ""
echo "SSH to your server and run:"
echo ""
echo "  tail -f /path/to/redfive/logs/webhook_debug.log"
echo ""
echo "OR if you want to see recent entries:"
echo ""
echo "  tail -20 /path/to/redfive/logs/webhook_debug.log"
echo ""
echo "OR search for RapidSOS requests:"
echo ""
echo "  grep -i 'rapidsos' /path/to/redfive/logs/webhook_debug.log"
echo ""
echo "---"
echo ""
echo "What to look for:"
echo "  ✓ Any POST requests from RapidSOS IP addresses"
echo "  ✓ Request headers containing 'RapidSOS' or 'edx'"
echo "  ✓ JSON payloads with 'alert_id'"
echo ""
echo "If you see NOTHING:"
echo "  → RapidSOS is NOT sending webhooks to your endpoint"
echo "  → This confirms subscriptions don't work for demo alerts"
echo ""
echo "If you see requests:"
echo "  → Webhooks ARE being sent!"
echo "  → The issue is in the processing/database layer"
echo ""
